In [2]:
import pandas as pd
import numpy as np
from datetime import datetime as dt
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', 60)

In [3]:
employee_df = pd.read_csv(r'Datasets\employee_data.csv')
insurance_df =  pd.read_csv(r'Datasets\insurance_data.csv')
vendor_df =  pd.read_csv(r'Datasets\vendor_data.csv')
employee_df

,AGENT_ID,AGENT_NAME,DATE_OF_JOINING,ADDRESS_LINE1,ADDRESS_LINE2,CITY,STATE,POSTAL_CODE,EMP_ROUTING_NUMBER,EMP_ACCT_NUMBER
0,AGENT00001,Ray Johns,1993-06-05,1402 Maggies Way,NaN,Waterbury Center,VT,5677,34584958,HKUN51252328472585
1,AGENT00002,Angelo Borjon,2005-12-27,414 Tanya Pass,NaN,Panama City,FL,32404,107363763,OPIS19290040088204
2,AGENT00003,Candy Spellman,2003-09-02,606 National Street,#306,Fayetteville,AR,72701,81744097,YSCJ67489688482590
3,AGENT00004,Mary Smith,2004-09-23,235 Hugh Thomas Drive,NaN,Panama City,FL,32404,67563771,ZANG21285355574581
4,AGENT00005,Mildred Diaz,2011-06-21,3426 Broadview Street,NaN,Montgomery,AL,36110,114951317,DZFS82244494451134
...,...,...,...,...,...,...,...,...,...,...
1195,AGENT01196,Myrtle Mccatty,2005-09-14,3553 Brandywine Street Northwest,NaN,Washington,DC,20008,32137938,EWBR19907574832501
1196,AGENT01197,John Dorsey,1993-12-04,2315 Chestnut Street,NaN,Montgomery,AL,36107,70796687,KGEJ74846009867837
1197,AGENT01198,Ruth Bigbee,1993-09-05,1983 Reidsville Street,NaN,Annapolis,MD,21401,124993912,RASV88064214164820
1198,AGENT01199,Tommie Camacho,2004-10-25,5821 Taft Street,NaN,Arvada,CO,80004,19424059,UOFO11656245339211
1199,AGENT01200,Virginia Stachura,1999-05-25,3579 2nd Avenue,NaN,Edgewater,MD,21037,12226940,ALYY24945545778511

In [4]:
insurance_df

,TXN_DATE_TIME,TRANSACTION_ID,CUSTOMER_ID,POLICY_NUMBER,POLICY_EFF_DT,LOSS_DT,REPORT_DT,INSURANCE_TYPE,PREMIUM_AMOUNT,CLAIM_AMOUNT,CUSTOMER_NAME,ADDRESS_LINE1,ADDRESS_LINE2,CITY,STATE,POSTAL_CODE,SSN,MARITAL_STATUS,AGE,TENURE,EMPLOYMENT_STATUS,NO_OF_FAMILY_MEMBERS,RISK_SEGMENTATION,HOUSE_TYPE,SOCIAL_CLASS,ROUTING_NUMBER,ACCT_NUMBER,CUSTOMER_EDUCATION_LEVEL,CLAIM_STATUS,INCIDENT_SEVERITY,AUTHORITY_CONTACTED,ANY_INJURY,POLICE_REPORT_AVAILABLE,INCIDENT_STATE,INCIDENT_CITY,INCIDENT_HOUR_OF_THE_DAY,AGENT_ID,VENDOR_ID
0,2020-06-01 00:00:00,TXN00000001,A00003822,PLC00008468,2015-06-23,2020-05-16,2020-05-21,Health,157.13,9000,Christopher Demarest,7701 West Saint John Road,#2010,Glendale,AZ,85308,087-11-1946,Y,54,89,Y,3,L,Own,LI,109134974,HXJP58258181908465,Bachelor,A,Major Loss,Police,0,1,GA,Savannah,4,AGENT00413,VNDR00556
1,2020-06-01 00:00:00,TXN00000002,A00008149,PLC00009594,2018-04-21,2020-05-13,2020-05-18,Property,141.71,26000,Ricardo Gatlin,8595 West 81st Drive,NaN,Arvada,CO,80005,685-33-3536,N,61,80,Y,4,L,Rent,MI,40125819,JUND46859540983731,Bachelor,A,Total Loss,Ambulance,1,0,AL,Montgomery,0,AGENT00769,VNDR00592
2,2020-06-01 00:00:00,TXN00000003,A00003172,PLC00007969,2019-10-03,2020-05-21,2020-05-26,Property,157.24,13000,Lashawn Engles,637 Britannia Drive,NaN,Vallejo,CA,94591,378-36-0672,N,47,68,Y,6,L,Rent,MI,99513168,WGZZ90128415227650,PhD,A,Total Loss,Police,0,1,CO,Grand Junction,19,AGENT00883,VNDR00031
3,2020-06-01 00:00:00,TXN00000004,A00007572,PLC00009292,2016-11-29,2020-05-14,2020-05-19,Health,172.87,16000,Steven Bassett,2803 River Drive,NaN,Thunderbolt,GA,31404,669-92-1861,Y,36,16,Y,7,L,Mortgage,MI,18429110,WIKE91555436351397,Masters,A,Minor Loss,Ambulance,0,0,GA,Savannah,12,AGENT00278,VNDR00075
4,2020-06-01 00:00:00,TXN00000005,A00008173,PLC00000204,2011-12-26,2020-05-17,2020-05-22,Travel,88.53,3000,Jason Rodriguez,7573 National Drive,NaN,Livermore,CA,94550,703-40-1033,Y,51,16,Y,2,M,Rent,HI,70752391,VYJW71311537294027,Masters,A,Major Loss,Police,0,1,TN,Nashville,18,AGENT00636,VNDR00472
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2021-06-30 00:00:00,TXN00009996,A00006029,PLC00007245,2014-04-11,2021-06-25,2021-06-26,Motor,105.75,1000,Patrick Hauman,126 Marjorie Lane,C,Manchester,CT,6042,711-20-5046,N,45,98,Y,3,M,Own,MI,89109346,FIDL48830187432471,PhD,A,Minor Loss,Ambulance,1,1,CT,Manchester,0,AGENT00779,NaN
9996,2021-06-30 00:00:00,TXN00009997,A00003555,PLC00002590,2015-08-25,2021-06-12,2021-06-17,Life,64.59,67000,Paula Noel,501 West Maple Street,#203,Fayetteville,AR,72701,069-65-6089,Y,52,92,Y,3,L,Mortgage,LI,89666038,ZWBN24881448170175,Masters,A,Total Loss,Police,1,0,MA,Worcester,6,AGENT00254,VNDR00598
9997,2021-06-30 00:00:00,TXN00009998,A00004230,PLC00006613,2018-10-11,2021-06-18,2021-06-23,Health,183.50,8000,Luis Clark,10980 Splendor Loop,NaN,Anchorage,AK,99577,743-01-9480,Y,53,32,Y,2,M,Mortgage,LI,34475591,ACXF69390753250566,Bachelor,A,Major Loss,NaN,1,1,OK,Oklahoma City,12,AGENT00786,VNDR00104
9998,2021-06-30 00:00:00,TXN00009999,A00006694,PLC00001781,2016-01-29,2021-06-16,2021-06-21,Motor,113.46,2000,Ryan Gordon,19 Heritage,NaN,Oakland,CA,94605,574-84-6660,Y,61,44,Y,7,M,Rent,MI,59003728,QNEI58902443815498,Bachelor,A,Total Loss,Ambulance,0,1,AR,Fayetteville,6,AGENT00927,VNDR00185
9999,2021-06-30 00:00:00,TXN00010000,A00000390,PLC00005197,2014-09-17,2021-06-21,2021-06-24,Mobile,8.22,300,Carol Clemons,3516 North Virginia Avenue,NaN,Oklahoma City,OK,73118,015-76-9874,Y,64,106,Y,2,M,Rent,MI,102750957,AGCL35862525415756,Bachelor,A,Total Loss,Ambulance,1,0,CT,Manchester,13,AGENT00118,VNDR00163

In [5]:
vendor_df

,VENDOR_ID,VENDOR_NAME,ADDRESS_LINE1,ADDRESS_LINE2,CITY,STATE,POSTAL_CODE
0,VNDR00001,"King, Proctor and Jones",2027 North Shannon Drive,#5,Fayetteville,AR,72703
1,VNDR00002,Garcia Ltd,5701 East Shirley Lane,NaN,Montgomery,AL,36117
2,VNDR00003,Cherry LLC,1217 Cottondale Road,NaN,Montgomery,AL,36109
3,VNDR00004,Mays-Benson,227 West Montgomery Cross Road,#736,Savannah,GA,31406
4,VNDR00005,Wilson PLC,23 North Hill Street,NaN,Nashville,TN,37210
...,...,...,...,...,...,...,...
595,VNDR00596,Rhodes-Mendez,1689 Fisher Pond Road,NaN,Saint Albans City,VT,5478
596,VNDR00597,Ortiz-Donovan,140 South Hill Avenue,#305,Fayetteville,AR,72701
597,VNDR00598,"Newton, Hodges and Henry",32512 Christine Drive,NaN,Union City,CA,94587
598,VNDR00599,Reeves-Leonard,12420 West Montebello Avenue,NaN,Litchfield Park,AZ,85340
599,VNDR00600,"Jacobs, Fox and Torres",2426 East Onyx Trail,#6,Fayetteville,AR,72701

In [6]:
employee_df.columns = ['AGENT_ID', 'AGENT_NAME', 'DATE_OF_JOINING', 'AGENT_ADDRESS_LINE1',
                        'AGENT_ADDRESS_LINE2', 'AGENT_CITY', 'AGENT_STATE', 'AGENT_POSTAL_CODE', 'EMP_ROUTING_NUMBER',
                        'EMP_ACCT_NUMBER']

In [7]:
vendor_df.columns = ['VENDOR_'+col if 'VENDOR' not in col else col for col in vendor_df.columns]

# Handling Missing values

In [29]:
def missing_values(df):
    dic = {'ColumnName':[], 'MissingValues':[], 'Percentage':[]}
    for col in df.columns:
        dic['ColumnName'].append(col)
        null = df[col].isna().sum()
        dic['MissingValues'].append(null)
        dic['Percentage'].append((null/df.shape[0])*100)
    return pd.DataFrame(dic).sort_values('Percentage', ascending= False)

In [28]:
insurance_df

,TXN_DATE_TIME,TRANSACTION_ID,CUSTOMER_ID,POLICY_NUMBER,POLICY_EFF_DT,LOSS_DT,REPORT_DT,INSURANCE_TYPE,PREMIUM_AMOUNT,CLAIM_AMOUNT,CUSTOMER_NAME,ADDRESS_LINE1,ADDRESS_LINE2,CITY,STATE,POSTAL_CODE,SSN,MARITAL_STATUS,AGE,TENURE,EMPLOYMENT_STATUS,NO_OF_FAMILY_MEMBERS,RISK_SEGMENTATION,HOUSE_TYPE,SOCIAL_CLASS,ROUTING_NUMBER,ACCT_NUMBER,CUSTOMER_EDUCATION_LEVEL,CLAIM_STATUS,INCIDENT_SEVERITY,AUTHORITY_CONTACTED,ANY_INJURY,POLICE_REPORT_AVAILABLE,INCIDENT_STATE,INCIDENT_CITY,INCIDENT_HOUR_OF_THE_DAY,AGENT_ID,VENDOR_ID
0,2020-06-01 00:00:00,TXN00000001,A00003822,PLC00008468,2015-06-23,2020-05-16,2020-05-21,Health,157.13,9000,Christopher Demarest,7701 West Saint John Road,#2010,Glendale,AZ,85308,087-11-1946,Y,54,89,Y,3,L,Own,LI,109134974,HXJP58258181908465,Bachelor,A,Major Loss,Police,0,1,GA,Savannah,4,AGENT00413,VNDR00556
1,2020-06-01 00:00:00,TXN00000002,A00008149,PLC00009594,2018-04-21,2020-05-13,2020-05-18,Property,141.71,26000,Ricardo Gatlin,8595 West 81st Drive,NaN,Arvada,CO,80005,685-33-3536,N,61,80,Y,4,L,Rent,MI,40125819,JUND46859540983731,Bachelor,A,Total Loss,Ambulance,1,0,AL,Montgomery,0,AGENT00769,VNDR00592
2,2020-06-01 00:00:00,TXN00000003,A00003172,PLC00007969,2019-10-03,2020-05-21,2020-05-26,Property,157.24,13000,Lashawn Engles,637 Britannia Drive,NaN,Vallejo,CA,94591,378-36-0672,N,47,68,Y,6,L,Rent,MI,99513168,WGZZ90128415227650,PhD,A,Total Loss,Police,0,1,CO,Grand Junction,19,AGENT00883,VNDR00031
3,2020-06-01 00:00:00,TXN00000004,A00007572,PLC00009292,2016-11-29,2020-05-14,2020-05-19,Health,172.87,16000,Steven Bassett,2803 River Drive,NaN,Thunderbolt,GA,31404,669-92-1861,Y,36,16,Y,7,L,Mortgage,MI,18429110,WIKE91555436351397,Masters,A,Minor Loss,Ambulance,0,0,GA,Savannah,12,AGENT00278,VNDR00075
4,2020-06-01 00:00:00,TXN00000005,A00008173,PLC00000204,2011-12-26,2020-05-17,2020-05-22,Travel,88.53,3000,Jason Rodriguez,7573 National Drive,NaN,Livermore,CA,94550,703-40-1033,Y,51,16,Y,2,M,Rent,HI,70752391,VYJW71311537294027,Masters,A,Major Loss,Police,0,1,TN,Nashville,18,AGENT00636,VNDR00472
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2021-06-30 00:00:00,TXN00009996,A00006029,PLC00007245,2014-04-11,2021-06-25,2021-06-26,Motor,105.75,1000,Patrick Hauman,126 Marjorie Lane,C,Manchester,CT,6042,711-20-5046,N,45,98,Y,3,M,Own,MI,89109346,FIDL48830187432471,PhD,A,Minor Loss,Ambulance,1,1,CT,Manchester,0,AGENT00779,NaN
9996,2021-06-30 00:00:00,TXN00009997,A00003555,PLC00002590,2015-08-25,2021-06-12,2021-06-17,Life,64.59,67000,Paula Noel,501 West Maple Street,#203,Fayetteville,AR,72701,069-65-6089,Y,52,92,Y,3,L,Mortgage,LI,89666038,ZWBN24881448170175,Masters,A,Total Loss,Police,1,0,MA,Worcester,6,AGENT00254,VNDR00598
9997,2021-06-30 00:00:00,TXN00009998,A00004230,PLC00006613,2018-10-11,2021-06-18,2021-06-23,Health,183.50,8000,Luis Clark,10980 Splendor Loop,NaN,Anchorage,AK,99577,743-01-9480,Y,53,32,Y,2,M,Mortgage,LI,34475591,ACXF69390753250566,Bachelor,A,Major Loss,NaN,1,1,OK,Oklahoma City,12,AGENT00786,VNDR00104
9998,2021-06-30 00:00:00,TXN00009999,A00006694,PLC00001781,2016-01-29,2021-06-16,2021-06-21,Motor,113.46,2000,Ryan Gordon,19 Heritage,NaN,Oakland,CA,94605,574-84-6660,Y,61,44,Y,7,M,Rent,MI,59003728,QNEI58902443815498,Bachelor,A,Total Loss,Ambulance,0,1,AR,Fayetteville,6,AGENT00927,VNDR00185
9999,2021-06-30 00:00:00,TXN00010000,A00000390,PLC00005197,2014-09-17,2021-06-21,2021-06-24,Mobile,8.22,300,Carol Clemons,3516 North Virginia Avenue,NaN,Oklahoma City,OK,73118,015-76-9874,Y,64,106,Y,2,M,Rent,MI,102750957,AGCL35862525415756,Bachelor,A,Total Loss,Ambulance,1,0,CT,Manchester,13,AGENT00118,VNDR00163

In [30]:
insurance_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 38 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   TXN_DATE_TIME             10000 non-null  object
 1   TRANSACTION_ID            10000 non-null  object
 2   CUSTOMER_ID               10000 non-null  object
 3   POLICY_NUMBER             10000 non-null  object
 4   POLICY_EFF_DT             10000 non-null  object
 5   LOSS_DT                   10000 non-null  object
 6   REPORT_DT                 10000 non-null  object
 7   INSURANCE_TYPE            10000 non-null  object
 8   PREMIUM_AMOUNT            10000 non-null  float64
 9   CLAIM_AMOUNT              10000 non-null  int64
 10  CUSTOMER_NAME             10000 non-null  object
 11  ADDRESS_LINE1             10000 non-null  object
 12  ADDRESS_LINE2             1495 non-null   object
 13  CITY                      9946 non-null   object
 14  STATE                     10000 non-null  object
 15  POSTAL_CODE               10000 non-null  int64
 16  SSN                       10000 non-null  object
 17  MARITAL_STATUS            10000 non-null  object
 18  AGE                       10000 non-null  int64
 19  TENURE                    10000 non-null  int64
 20  EMPLOYMENT_STATUS         10000 non-null  object
 21  NO_OF_FAMILY_MEMBERS      10000 non-null  int64
 22  RISK_SEGMENTATION         10000 non-null  object
 23  HOUSE_TYPE                10000 non-null  object
 24  SOCIAL_CLASS              10000 non-null  object
 25  ROUTING_NUMBER            10000 non-null  int64
 26  ACCT_NUMBER               10000 non-null  object
 27  CUSTOMER_EDUCATION_LEVEL  9471 non-null   object
 28  CLAIM_STATUS              10000 non-null  object
 29  INCIDENT_SEVERITY         10000 non-null  object
 30  AUTHORITY_CONTACTED       8055 non-null   object
 31  ANY_INJURY                10000 non-null  int64
 32  POLICE_REPORT_AVAILABLE   10000 non-null  int64
 33  INCIDENT_STATE            10000 non-null  object
 34  INCIDENT_CITY             9954 non-null   object
 35  INCIDENT_HOUR_OF_THE_DAY  10000 non-null  int64
 36  AGENT_ID                  10000 non-null  object
 37  VENDOR_ID                 6755 non-null   object
dtypes: float64(1), int64(9), object(28)
memory usage: 2.9+ MB

In [31]:
insurance_df.describe().T

,count,mean,std,min,25%,50%,75%,max
PREMIUM_AMOUNT,10000.0,8.850859e+01,4.831587e+01,6.0,6.201500e+01,8.883500e+01,1.219025e+02,200.0
CLAIM_AMOUNT,10000.0,1.656383e+04,2.203749e+04,100.0,2.000000e+03,7.000000e+03,2.100000e+04,100000.0
POSTAL_CODE,10000.0,4.828883e+04,3.246739e+04,1001.0,2.106100e+04,3.720600e+04,8.000400e+04,99669.0
AGE,10000.0,4.446610e+01,1.151683e+01,25.0,3.400000e+01,4.500000e+01,5.400000e+01,64.0
TENURE,10000.0,6.294980e+01,3.289060e+01,6.0,3.400000e+01,6.400000e+01,9.200000e+01,119.0
NO_OF_FAMILY_MEMBERS,10000.0,4.488400e+00,1.712588e+00,2.0,3.000000e+00,4.000000e+00,6.000000e+00,7.0
ROUTING_NUMBER,10000.0,7.052882e+07,3.451879e+07,10000744.0,4.071761e+07,7.036614e+07,1.000638e+08,129998077.0
ANY_INJURY,10000.0,6.991000e-01,4.586722e-01,0.0,0.000000e+00,1.000000e+00,1.000000e+00,1.0
POLICE_REPORT_AVAILABLE,10000.0,6.928000e-01,4.613561e-01,0.0,0.000000e+00,1.000000e+00,1.000000e+00,1.0
INCIDENT_HOUR_OF_THE_DAY,10000.0,1.160400e+01,6.877101e+00,0.0,6.000000e+00,1.200000e+01,1.800000e+01,23.0

In [32]:
missing_values(insurance_df)

                  ColumnName  MissingValues  Percentage
12             ADDRESS_LINE2           8505       85.05
37                 VENDOR_ID           3245       32.45
30       AUTHORITY_CONTACTED           1945       19.45
27  CUSTOMER_EDUCATION_LEVEL            529        5.29
13                      CITY             54        0.54
34             INCIDENT_CITY             46        0.46
22         RISK_SEGMENTATION              0        0.00
23                HOUSE_TYPE              0        0.00
24              SOCIAL_CLASS              0        0.00
25            ROUTING_NUMBER              0        0.00
26               ACCT_NUMBER              0        0.00
28              CLAIM_STATUS              0        0.00
20         EMPLOYMENT_STATUS              0        0.00
29         INCIDENT_SEVERITY              0        0.00
31                ANY_INJURY              0        0.00
32   POLICE_REPORT_AVAILABLE              0        0.00
33            INCIDENT_STATE              0        0.00
35  INCIDENT_HOUR_OF_THE_DAY              0        0.00
36                  AGENT_ID              0        0.00
21      NO_OF_FAMILY_MEMBERS              0        0.00
0              TXN_DATE_TIME              0        0.00
1             TRANSACTION_ID              0        0.00
8             PREMIUM_AMOUNT              0        0.00
2                CUSTOMER_ID              0        0.00
3              POLICY_NUMBER              0        0.00
4              POLICY_EFF_DT              0        0.00
5                    LOSS_DT              0        0.00
6                  REPORT_DT              0        0.00
7             INSURANCE_TYPE              0        0.00
9               CLAIM_AMOUNT              0        0.00
18                       AGE              0        0.00
10             CUSTOMER_NAME              0        0.00
11             ADDRESS_LINE1              0        0.00
14                     STATE              0        0.00
15               POSTAL_CODE              0        0.00
16                       SSN              0        0.00
17            MARITAL_STATUS              0        0.00
19                    TENURE              0        0.00

In [33]:
def fill_city(city, incident):
    if type(city)== float:
        return incident
    else:
        return city
insurance_df['CITY']=insurance_df.apply(lambda row: fill_city(row['CITY'], row['INCIDENT_CITY']), axis = 1)

In [34]:
def fill_incident_city(city, incident):
    if type(incident)== float:
        return city
    else:
        return incident
insurance_df['INCIDENT_CITY']=insurance_df.apply(lambda row: fill_incident_city(row['CITY'], row['INCIDENT_CITY']), axis = 1)

In [67]:
vendor_ratio = insurance_df['VENDOR_ID'].value_counts(normalize=True)

def fill_missing_vendor_ids(df, column_name, ratio):
    # Get the indices where the column has NaN values
    missing_indices = df[column_name].isna()
    
    # Use np.random.choice to randomly select a value based on the ratio
    df.loc[missing_indices, column_name] = np.random.choice(
        ratio.index, size=missing_indices.sum(), p=ratio.values
    )

# Apply the function to fill missing values in 'VENDOR_ID' column
fill_missing_vendor_ids(insurance_df, 'VENDOR_ID', vendor_ratio)

In [49]:
insurance_df.AUTHORITY_CONTACTED.value_counts(normalize=True)

AUTHORITY_CONTACTED
Ambulance    0.506766
Police       0.370205
Other        0.123029
Name: proportion, dtype: float64

In [50]:
insurance_df[insurance_df.AUTHORITY_CONTACTED.isna()==True]['INSURANCE_TYPE' ].value_counts(normalize=True)

INSURANCE_TYPE
Life        0.177378
Motor       0.171208
Health      0.166581
Mobile      0.166581
Property    0.160925
Travel      0.157326
Name: proportion, dtype: float64

In [56]:
def fill_authority(insurance_type, authority):
    if type(authority)==float:
        if insurance_type in ['Life', 'Health', 'Travel']:
            return 'Ambulance'

        elif insurance_type in ['Motor', 'Property']:
            return 'Police'
        else:
            return 'Other'
    else:
        return authority
    

insurance_df.AUTHORITY_CONTACTED  =insurance_df.apply(lambda row: fill_authority(row['INSURANCE_TYPE'], row['AUTHORITY_CONTACTED']), axis = 1)

In [60]:
insurance_df

,TXN_DATE_TIME,TRANSACTION_ID,CUSTOMER_ID,POLICY_NUMBER,POLICY_EFF_DT,LOSS_DT,REPORT_DT,INSURANCE_TYPE,PREMIUM_AMOUNT,CLAIM_AMOUNT,CUSTOMER_NAME,ADDRESS_LINE1,ADDRESS_LINE2,CITY,STATE,POSTAL_CODE,SSN,MARITAL_STATUS,AGE,TENURE,EMPLOYMENT_STATUS,NO_OF_FAMILY_MEMBERS,RISK_SEGMENTATION,HOUSE_TYPE,SOCIAL_CLASS,ROUTING_NUMBER,ACCT_NUMBER,CUSTOMER_EDUCATION_LEVEL,CLAIM_STATUS,INCIDENT_SEVERITY,AUTHORITY_CONTACTED,ANY_INJURY,POLICE_REPORT_AVAILABLE,INCIDENT_STATE,INCIDENT_CITY,INCIDENT_HOUR_OF_THE_DAY,AGENT_ID,VENDOR_ID
0,2020-06-01 00:00:00,TXN00000001,A00003822,PLC00008468,2015-06-23,2020-05-16,2020-05-21,Health,157.13,9000,Christopher Demarest,7701 West Saint John Road,#2010,Glendale,AZ,85308,087-11-1946,Y,54,89,Y,3,L,Own,LI,109134974,HXJP58258181908465,Bachelor,A,Major Loss,Police,0,1,GA,Savannah,4,AGENT00413,VNDR00556
1,2020-06-01 00:00:00,TXN00000002,A00008149,PLC00009594,2018-04-21,2020-05-13,2020-05-18,Property,141.71,26000,Ricardo Gatlin,8595 West 81st Drive,NaN,Arvada,CO,80005,685-33-3536,N,61,80,Y,4,L,Rent,MI,40125819,JUND46859540983731,Bachelor,A,Total Loss,Ambulance,1,0,AL,Montgomery,0,AGENT00769,VNDR00592
2,2020-06-01 00:00:00,TXN00000003,A00003172,PLC00007969,2019-10-03,2020-05-21,2020-05-26,Property,157.24,13000,Lashawn Engles,637 Britannia Drive,NaN,Vallejo,CA,94591,378-36-0672,N,47,68,Y,6,L,Rent,MI,99513168,WGZZ90128415227650,PhD,A,Total Loss,Police,0,1,CO,Grand Junction,19,AGENT00883,VNDR00031
3,2020-06-01 00:00:00,TXN00000004,A00007572,PLC00009292,2016-11-29,2020-05-14,2020-05-19,Health,172.87,16000,Steven Bassett,2803 River Drive,NaN,Thunderbolt,GA,31404,669-92-1861,Y,36,16,Y,7,L,Mortgage,MI,18429110,WIKE91555436351397,Masters,A,Minor Loss,Ambulance,0,0,GA,Savannah,12,AGENT00278,VNDR00075
4,2020-06-01 00:00:00,TXN00000005,A00008173,PLC00000204,2011-12-26,2020-05-17,2020-05-22,Travel,88.53,3000,Jason Rodriguez,7573 National Drive,NaN,Livermore,CA,94550,703-40-1033,Y,51,16,Y,2,M,Rent,HI,70752391,VYJW71311537294027,Masters,A,Major Loss,Police,0,1,TN,Nashville,18,AGENT00636,VNDR00472
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2021-06-30 00:00:00,TXN00009996,A00006029,PLC00007245,2014-04-11,2021-06-25,2021-06-26,Motor,105.75,1000,Patrick Hauman,126 Marjorie Lane,C,Manchester,CT,6042,711-20-5046,N,45,98,Y,3,M,Own,MI,89109346,FIDL48830187432471,PhD,A,Minor Loss,Ambulance,1,1,CT,Manchester,0,AGENT00779,NaN
9996,2021-06-30 00:00:00,TXN00009997,A00003555,PLC00002590,2015-08-25,2021-06-12,2021-06-17,Life,64.59,67000,Paula Noel,501 West Maple Street,#203,Fayetteville,AR,72701,069-65-6089,Y,52,92,Y,3,L,Mortgage,LI,89666038,ZWBN24881448170175,Masters,A,Total Loss,Police,1,0,MA,Worcester,6,AGENT00254,VNDR00598
9997,2021-06-30 00:00:00,TXN00009998,A00004230,PLC00006613,2018-10-11,2021-06-18,2021-06-23,Health,183.50,8000,Luis Clark,10980 Splendor Loop,NaN,Anchorage,AK,99577,743-01-9480,Y,53,32,Y,2,M,Mortgage,LI,34475591,ACXF69390753250566,Bachelor,A,Major Loss,Ambulance,1,1,OK,Oklahoma City,12,AGENT00786,VNDR00104
9998,2021-06-30 00:00:00,TXN00009999,A00006694,PLC00001781,2016-01-29,2021-06-16,2021-06-21,Motor,113.46,2000,Ryan Gordon,19 Heritage,NaN,Oakland,CA,94605,574-84-6660,Y,61,44,Y,7,M,Rent,MI,59003728,QNEI58902443815498,Bachelor,A,Total Loss,Ambulance,0,1,AR,Fayetteville,6,AGENT00927,VNDR00185
9999,2021-06-30 00:00:00,TXN00010000,A00000390,PLC00005197,2014-09-17,2021-06-21,2021-06-24,Mobile,8.22,300,Carol Clemons,3516 North Virginia Avenue,NaN,Oklahoma City,OK,73118,015-76-9874,Y,64,106,Y,2,M,Rent,MI,102750957,AGCL35862525415756,Bachelor,A,Total Loss,Ambulance,1,0,CT,Manchester,13,AGENT00118,VNDR00163

In [68]:
# Filling missing values in CUSTOMER_EDUCATION_LEVEL based on the ratio method.

education_ratio = insurance_df['CUSTOMER_EDUCATION_LEVEL'].value_counts(normalize=True)



def fill_missing_education_level(df, column_name, ratio):
    # Get the indices where the column has NaN values
    missing_indices = df[column_name].isna()
    
    # Use np.random.choice to randomly select a value based on the ratio
    df.loc[missing_indices, column_name] = np.random.choice(
        ratio.index, size=missing_indices.sum(), p=ratio.values
    )


fill_missing_education_level(insurance_df, 'CUSTOMER_EDUCATION_LEVEL', education_ratio)

In [69]:
missing_values(insurance_df)

                  ColumnName  MissingValues  Percentage
12             ADDRESS_LINE2           8505       85.05
0              TXN_DATE_TIME              0        0.00
28              CLAIM_STATUS              0        0.00
22         RISK_SEGMENTATION              0        0.00
23                HOUSE_TYPE              0        0.00
24              SOCIAL_CLASS              0        0.00
25            ROUTING_NUMBER              0        0.00
26               ACCT_NUMBER              0        0.00
27  CUSTOMER_EDUCATION_LEVEL              0        0.00
29         INCIDENT_SEVERITY              0        0.00
20         EMPLOYMENT_STATUS              0        0.00
30       AUTHORITY_CONTACTED              0        0.00
31                ANY_INJURY              0        0.00
32   POLICE_REPORT_AVAILABLE              0        0.00
33            INCIDENT_STATE              0        0.00
34             INCIDENT_CITY              0        0.00
35  INCIDENT_HOUR_OF_THE_DAY              0        0.00
36                  AGENT_ID              0        0.00
21      NO_OF_FAMILY_MEMBERS              0        0.00
19                    TENURE              0        0.00
1             TRANSACTION_ID              0        0.00
18                       AGE              0        0.00
2                CUSTOMER_ID              0        0.00
3              POLICY_NUMBER              0        0.00
4              POLICY_EFF_DT              0        0.00
5                    LOSS_DT              0        0.00
6                  REPORT_DT              0        0.00
7             INSURANCE_TYPE              0        0.00
8             PREMIUM_AMOUNT              0        0.00
9               CLAIM_AMOUNT              0        0.00
10             CUSTOMER_NAME              0        0.00
11             ADDRESS_LINE1              0        0.00
13                      CITY              0        0.00
14                     STATE              0        0.00
15               POSTAL_CODE              0        0.00
16                       SSN              0        0.00
17            MARITAL_STATUS              0        0.00
37                 VENDOR_ID              0        0.00

In [8]:
employee_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   AGENT_ID             1200 non-null   object
 1   AGENT_NAME           1200 non-null   object
 2   DATE_OF_JOINING      1200 non-null   object
 3   AGENT_ADDRESS_LINE1  1200 non-null   object
 4   AGENT_ADDRESS_LINE2  179 non-null    object
 5   AGENT_CITY           1193 non-null   object
 6   AGENT_STATE          1200 non-null   object
 7   AGENT_POSTAL_CODE    1200 non-null   int64
 8   EMP_ROUTING_NUMBER   1200 non-null   int64
 9   EMP_ACCT_NUMBER      1200 non-null   object
dtypes: int64(2), object(8)
memory usage: 93.9+ KB

# Merging DataFrame

In [70]:
df = pd.merge(insurance_df, employee_df, on='AGENT_ID')
final_df = pd.merge(df, vendor_df, on='VENDOR_ID', how='left')

final_df

,TXN_DATE_TIME,TRANSACTION_ID,CUSTOMER_ID,POLICY_NUMBER,POLICY_EFF_DT,LOSS_DT,REPORT_DT,INSURANCE_TYPE,PREMIUM_AMOUNT,CLAIM_AMOUNT,CUSTOMER_NAME,ADDRESS_LINE1,ADDRESS_LINE2,CITY,STATE,POSTAL_CODE,SSN,MARITAL_STATUS,AGE,TENURE,EMPLOYMENT_STATUS,NO_OF_FAMILY_MEMBERS,RISK_SEGMENTATION,HOUSE_TYPE,SOCIAL_CLASS,ROUTING_NUMBER,ACCT_NUMBER,CUSTOMER_EDUCATION_LEVEL,CLAIM_STATUS,INCIDENT_SEVERITY,AUTHORITY_CONTACTED,ANY_INJURY,POLICE_REPORT_AVAILABLE,INCIDENT_STATE,INCIDENT_CITY,INCIDENT_HOUR_OF_THE_DAY,AGENT_ID,VENDOR_ID,AGENT_NAME,DATE_OF_JOINING,AGENT_ADDRESS_LINE1,AGENT_ADDRESS_LINE2,AGENT_CITY,AGENT_STATE,AGENT_POSTAL_CODE,EMP_ROUTING_NUMBER,EMP_ACCT_NUMBER,VENDOR_NAME,VENDOR_ADDRESS_LINE1,VENDOR_ADDRESS_LINE2,VENDOR_CITY,VENDOR_STATE,VENDOR_POSTAL_CODE
0,2020-06-01 00:00:00,TXN00000001,A00003822,PLC00008468,2015-06-23,2020-05-16,2020-05-21,Health,157.13,9000,Christopher Demarest,7701 West Saint John Road,#2010,Glendale,AZ,85308,087-11-1946,Y,54,89,Y,3,L,Own,LI,109134974,HXJP58258181908465,Bachelor,A,Major Loss,Police,0,1,GA,Savannah,4,AGENT00413,VNDR00556,Amy Wangler,1994-01-06,584 Rural Hill Road,NaN,Nashville,TN,37217,35441155,LRZO53254369804934,Ramsey Inc,3114 West 20th Court,NaN,Panama City,FL,32405
1,2020-06-01 00:00:00,TXN00000002,A00008149,PLC00009594,2018-04-21,2020-05-13,2020-05-18,Property,141.71,26000,Ricardo Gatlin,8595 West 81st Drive,NaN,Arvada,CO,80005,685-33-3536,N,61,80,Y,4,L,Rent,MI,40125819,JUND46859540983731,Bachelor,A,Total Loss,Ambulance,1,0,AL,Montgomery,0,AGENT00769,VNDR00592,Jessica Montez,2004-05-28,6114 West Glenn Drive,#1,Glendale,AZ,85301,44055451,XBYG14382904542874,"Morales, Campbell and Washington",42 West Louise Street,B,Fayetteville,AR,72701
2,2020-06-01 00:00:00,TXN00000003,A00003172,PLC00007969,2019-10-03,2020-05-21,2020-05-26,Property,157.24,13000,Lashawn Engles,637 Britannia Drive,NaN,Vallejo,CA,94591,378-36-0672,N,47,68,Y,6,L,Rent,MI,99513168,WGZZ90128415227650,PhD,A,Total Loss,Police,0,1,CO,Grand Junction,19,AGENT00883,VNDR00031,Howard Smith,2004-08-01,2500 Snowdoun Chambers Road,NaN,Montgomery,AL,36105,55770246,WRXH14597428306333,Johnson Ltd,2619 North Quality Lane,#315,Fayetteville,AR,72703
3,2020-06-01 00:00:00,TXN00000004,A00007572,PLC00009292,2016-11-29,2020-05-14,2020-05-19,Health,172.87,16000,Steven Bassett,2803 River Drive,NaN,Thunderbolt,GA,31404,669-92-1861,Y,36,16,Y,7,L,Mortgage,MI,18429110,WIKE91555436351397,Masters,A,Minor Loss,Ambulance,0,0,GA,Savannah,12,AGENT00278,VNDR00075,Patricia Tucker,2007-06-12,313 Lone Oak Drive,NaN,Norman,OK,73071,87652976,YEPN16077902472499,Blackwell-Foster,3609 Meadow Drive,NaN,Nashville,TN,37215
4,2020-06-01 00:00:00,TXN00000005,A00008173,PLC00000204,2011-12-26,2020-05-17,2020-05-22,Travel,88.53,3000,Jason Rodriguez,7573 National Drive,NaN,Livermore,CA,94550,703-40-1033,Y,51,16,Y,2,M,Rent,HI,70752391,VYJW71311537294027,Masters,A,Major Loss,Police,0,1,TN,Nashville,18,AGENT00636,VNDR00472,Brenda Bean,2010-01-19,120 Wells Avenue,NaN,Glen Burnie,MD,21061,76119019,HZBK86544578578547,Evans-Scott,4001 19th Place Northeast,NaN,Washington,DC,20018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2021-06-30 00:00:00,TXN00009996,A00006029,PLC00007245,2014-04-11,2021-06-25,2021-06-26,Motor,105.75,1000,Patrick Hauman,126 Marjorie Lane,C,Manchester,CT,6042,711-20-5046,N,45,98,Y,3,M,Own,MI,89109346,FIDL48830187432471,PhD,A,Minor Loss,Ambulance,1,1,CT,Manchester,0,AGENT00779,VNDR00001,Melissa Scott,1990-10-12,2723 East Joyce Boulevard,NaN,Fayetteville,AR,72703,35413882,LFOJ76068590051807,"King, Proctor and Jones",2027 North Shannon Drive,#5,Fayetteville,AR,72703
9996,2021-06-30 00:00:00,TXN00009997,A00003555,PLC00002590,2015-08-25,2021-06-12,2021-06-17,Life,64.59,67000,Paula Noel,501 West Maple Street,#203,Fayetteville,AR,72701,069-65-6089,Y,52,92,Y,3,L,Mortgage,LI,89666038,ZWBN24881448170175,Masters,A,Total Loss,Police,1,0,MA,Worcester,6,AGENT00254,VNDR00598,Freda Dudley,2013-01-17,1363 Dean Forest Road,NaN,Savannah,GA,31405,91206790,AHEF60771774635030,"Newton, Hodges and Henry",32512 Christine Drive,NaN,Union City,CA,94587
9997,2021-06-30 00:00:00,TXN00009998,A00004230,PLC00006613,2018-10-11,2021-06-18,2021-06-23,Health,183.50,8000,Luis Clark,10980 Splendor Loop,NaN,Anchorage,AK,99577,743-01-9480,Y,53,32,Y,2,M,Mortgage,LI,34475591,ACXF69390753250566,Bachelor,A,Major Loss,Ambulance,1,1,OK,Oklahoma City,12,AGENT00786,VNDR00104,Victor Perrin,1993-02-11,9912 Shirewick Way,NaN,Louisville,KY,40272,115241097,WREH18805592939657,Reese-Mckinney,20 Garfield Street,NaN,Needham,MA,2492
9998,2021-06-30 00:00:00,TXN00009999,A00006694,PLC00001781,2016-01-29,2021-06-16,2021-06-21,Motor,113.46,2000,Ryan Gordon,19 Heritage,NaN,Oakland,CA,94605,574-84-6660,Y,61,44,Y,7,M,Rent,MI,59003728,QNEI58902443815498,Bachelor,A,Total Loss,Ambulance,0,1,AR,Fayetteville,6,AGENT00927,VNDR00185,Maria Lynn,2010-04-16,302 East Granada Street,NaN,Fayetteville,AR,72703,13995380,AAZI21883736448048,"Harmon, Manning and Bradley",1823 Dinger Road,NaN,Annapolis,MD,21402
9999,2021-06-30 00:00:00,TXN00010000,A00000390,PLC00005197,2014-09-17,2021-06-21,2021-06-24,Mobile,8.22,300,Carol Clemons,3516 North Virginia Avenue,NaN,Oklahoma City,OK,73118,015-76-9874,Y,64,106,Y,2,M,Rent,MI,102750957,AGCL35862525415756,Bachelor,A,Total Loss,Ambulance,1,0,CT,Manchester,13,AGENT00118,VNDR00163,Carl Balado,2007-10-26,1713 Apian Way,NaN,Edmond,OK,73003,39790996,RPES05613584687957,Foster-Sanchez,4255 Tanager Common,NaN,Fremont,CA,94555

In [71]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 53 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   TXN_DATE_TIME             10000 non-null  object
 1   TRANSACTION_ID            10000 non-null  object
 2   CUSTOMER_ID               10000 non-null  object
 3   POLICY_NUMBER             10000 non-null  object
 4   POLICY_EFF_DT             10000 non-null  object
 5   LOSS_DT                   10000 non-null  object
 6   REPORT_DT                 10000 non-null  object
 7   INSURANCE_TYPE            10000 non-null  object
 8   PREMIUM_AMOUNT            10000 non-null  float64
 9   CLAIM_AMOUNT              10000 non-null  int64
 10  CUSTOMER_NAME             10000 non-null  object
 11  ADDRESS_LINE1             10000 non-null  object
 12  ADDRESS_LINE2             1495 non-null   object
 13  CITY                      10000 non-null  object
 14  STATE                     10000 non-null  object
 15  POSTAL_CODE               10000 non-null  int64
 16  SSN                       10000 non-null  object
 17  MARITAL_STATUS            10000 non-null  object
 18  AGE                       10000 non-null  int64
 19  TENURE                    10000 non-null  int64
 20  EMPLOYMENT_STATUS         10000 non-null  object
 21  NO_OF_FAMILY_MEMBERS      10000 non-null  int64
 22  RISK_SEGMENTATION         10000 non-null  object
 23  HOUSE_TYPE                10000 non-null  object
 24  SOCIAL_CLASS              10000 non-null  object
 25  ROUTING_NUMBER            10000 non-null  int64
 26  ACCT_NUMBER               10000 non-null  object
 27  CUSTOMER_EDUCATION_LEVEL  10000 non-null  object
 28  CLAIM_STATUS              10000 non-null  object
 29  INCIDENT_SEVERITY         10000 non-null  object
 30  AUTHORITY_CONTACTED       10000 non-null  object
 31  ANY_INJURY                10000 non-null  int64
 32  POLICE_REPORT_AVAILABLE   10000 non-null  int64
 33  INCIDENT_STATE            10000 non-null  object
 34  INCIDENT_CITY             10000 non-null  object
 35  INCIDENT_HOUR_OF_THE_DAY  10000 non-null  int64
 36  AGENT_ID                  10000 non-null  object
 37  VENDOR_ID                 10000 non-null  object
 38  AGENT_NAME                10000 non-null  object
 39  DATE_OF_JOINING           10000 non-null  object
 40  AGENT_ADDRESS_LINE1       10000 non-null  object
 41  AGENT_ADDRESS_LINE2       1451 non-null   object
 42  AGENT_CITY                9946 non-null   object
 43  AGENT_STATE               10000 non-null  object
 44  AGENT_POSTAL_CODE         10000 non-null  int64
 45  EMP_ROUTING_NUMBER        10000 non-null  int64
 46  EMP_ACCT_NUMBER           10000 non-null  object
 47  VENDOR_NAME               10000 non-null  object
 48  VENDOR_ADDRESS_LINE1      10000 non-null  object
 49  VENDOR_ADDRESS_LINE2      1686 non-null   object
 50  VENDOR_CITY               9943 non-null   object
 51  VENDOR_STATE              10000 non-null  object
 52  VENDOR_POSTAL_CODE        10000 non-null  int64
dtypes: float64(1), int64(12), object(40)
memory usage: 4.0+ MB

In [72]:
final_df.describe().T

,count,mean,std,min,25%,50%,75%,max
PREMIUM_AMOUNT,10000.0,8.850859e+01,4.831587e+01,6.0,6.201500e+01,8.883500e+01,1.219025e+02,200.0
CLAIM_AMOUNT,10000.0,1.656383e+04,2.203749e+04,100.0,2.000000e+03,7.000000e+03,2.100000e+04,100000.0
POSTAL_CODE,10000.0,4.828883e+04,3.246739e+04,1001.0,2.106100e+04,3.720600e+04,8.000400e+04,99669.0
AGE,10000.0,4.446610e+01,1.151683e+01,25.0,3.400000e+01,4.500000e+01,5.400000e+01,64.0
TENURE,10000.0,6.294980e+01,3.289060e+01,6.0,3.400000e+01,6.400000e+01,9.200000e+01,119.0
NO_OF_FAMILY_MEMBERS,10000.0,4.488400e+00,1.712588e+00,2.0,3.000000e+00,4.000000e+00,6.000000e+00,7.0
ROUTING_NUMBER,10000.0,7.052882e+07,3.451879e+07,10000744.0,4.071761e+07,7.036614e+07,1.000638e+08,129998077.0
ANY_INJURY,10000.0,6.991000e-01,4.586722e-01,0.0,0.000000e+00,1.000000e+00,1.000000e+00,1.0
POLICE_REPORT_AVAILABLE,10000.0,6.928000e-01,4.613561e-01,0.0,0.000000e+00,1.000000e+00,1.000000e+00,1.0
INCIDENT_HOUR_OF_THE_DAY,10000.0,1.160400e+01,6.877101e+00,0.0,6.000000e+00,1.200000e+01,1.800000e+01,23.0
AGENT_POSTAL_CODE,10000.0,5.029217e+04,3.336995e+04,1007.0,2.106100e+04,3.721100e+04,8.100700e+04,99577.0
EMP_ROUTING_NUMBER,10000.0,7.099599e+07,3.452747e+07,10022146.0,4.007634e+07,7.258413e+07,1.010319e+08,129922616.0
VENDOR_POSTAL_CODE,10000.0,4.988485e+04,3.181155e+04,1104.0,2.140200e+04,3.722100e+04,8.000300e+04,99603.0

In [ ]:

def ratio_based_filling(df, column_name, ratio):
    ratio = insurance_df[column_name].value_counts(normalize=True)
    # Get the indices where the column has NaN values
    missing_indices = df[column_name].isna()
    
    # Use np.random.choice to randomly select a value based on the ratio
    df.loc[missing_indices, column_name] = np.random.choice(
        ratio.index, size=missing_indices.sum(), p=ratio.values
    )


fill_missing_vendor_ids(insurance_df, 'VENDOR_ID',)

In [73]:
final_df.nunique()

TXN_DATE_TIME                 395
TRANSACTION_ID              10000
CUSTOMER_ID                 10000
POLICY_NUMBER               10000
POLICY_EFF_DT                3306
LOSS_DT                       414
REPORT_DT                     409
INSURANCE_TYPE                  6
PREMIUM_AMOUNT               6550
CLAIM_AMOUNT                  107
CUSTOMER_NAME                9880
ADDRESS_LINE1                3092
ADDRESS_LINE2                 256
CITY                          413
STATE                          16
POSTAL_CODE                   669
SSN                         10000
MARITAL_STATUS                  2
AGE                            40
TENURE                        114
EMPLOYMENT_STATUS               2
NO_OF_FAMILY_MEMBERS            6
RISK_SEGMENTATION               3
HOUSE_TYPE                      3
SOCIAL_CLASS                    3
ROUTING_NUMBER               9995
ACCT_NUMBER                 10000
CUSTOMER_EDUCATION_LEVEL        6
CLAIM_STATUS                    2
INCIDENT_SEVERITY               3
AUTHORITY_CONTACTED             3
ANY_INJURY                      2
POLICE_REPORT_AVAILABLE         2
INCIDENT_STATE                 16
INCIDENT_CITY                 406
INCIDENT_HOUR_OF_THE_DAY       24
AGENT_ID                     1200
VENDOR_ID                     407
AGENT_NAME                   1198
DATE_OF_JOINING              1125
AGENT_ADDRESS_LINE1          1002
AGENT_ADDRESS_LINE2           114
AGENT_CITY                    203
AGENT_STATE                    16
AGENT_POSTAL_CODE             361
EMP_ROUTING_NUMBER           1200
EMP_ACCT_NUMBER              1200
VENDOR_NAME                   403
VENDOR_ADDRESS_LINE1          378
VENDOR_ADDRESS_LINE2           49
VENDOR_CITY                   100
VENDOR_STATE                   16
VENDOR_POSTAL_CODE            191
dtype: int64

##### Removing the columns having Unique values

In [74]:
# Unique value columns are not affect the model. So that, Removing Unique values columns
unique_col = [col for col in final_df.columns if final_df[col].nunique()==final_df.shape[0]]
print('Shape of the DataFrame before removing the columns', final_df.shape)
print('Droped Column names:', len(unique_col))
final_df.drop(unique_col, axis = 1, inplace = True)
print('Shape of the DataFrame After removing the columns', final_df.shape)

Shape of the DataFrame before removing the columns (10000, 53)
Droped Column names: 5
Shape of the DataFrame After removing the columns (10000, 48)

##### Removing the columns with missing values more than 50%

In [75]:
null_df = missing_values(final_df)
null_df

                  ColumnName  MissingValues  Percentage
36       AGENT_ADDRESS_LINE2           8549       85.49
9              ADDRESS_LINE2           8505       85.05
44      VENDOR_ADDRESS_LINE2           8314       83.14
45               VENDOR_CITY             57        0.57
37                AGENT_CITY             54        0.54
35       AGENT_ADDRESS_LINE1              0        0.00
27   POLICE_REPORT_AVAILABLE              0        0.00
28            INCIDENT_STATE              0        0.00
29             INCIDENT_CITY              0        0.00
30  INCIDENT_HOUR_OF_THE_DAY              0        0.00
31                  AGENT_ID              0        0.00
32                 VENDOR_ID              0        0.00
33                AGENT_NAME              0        0.00
34           DATE_OF_JOINING              0        0.00
0              TXN_DATE_TIME              0        0.00
25       AUTHORITY_CONTACTED              0        0.00
38               AGENT_STATE              0        0.00
39         AGENT_POSTAL_CODE              0        0.00
40        EMP_ROUTING_NUMBER              0        0.00
41           EMP_ACCT_NUMBER              0        0.00
42               VENDOR_NAME              0        0.00
43      VENDOR_ADDRESS_LINE1              0        0.00
46              VENDOR_STATE              0        0.00
26                ANY_INJURY              0        0.00
24         INCIDENT_SEVERITY              0        0.00
1              POLICY_EFF_DT              0        0.00
12               POSTAL_CODE              0        0.00
2                    LOSS_DT              0        0.00
3                  REPORT_DT              0        0.00
4             INSURANCE_TYPE              0        0.00
5             PREMIUM_AMOUNT              0        0.00
6               CLAIM_AMOUNT              0        0.00
7              CUSTOMER_NAME              0        0.00
8              ADDRESS_LINE1              0        0.00
10                      CITY              0        0.00
11                     STATE              0        0.00
13            MARITAL_STATUS              0        0.00
23              CLAIM_STATUS              0        0.00
14                       AGE              0        0.00
15                    TENURE              0        0.00
16         EMPLOYMENT_STATUS              0        0.00
17      NO_OF_FAMILY_MEMBERS              0        0.00
18         RISK_SEGMENTATION              0        0.00
19                HOUSE_TYPE              0        0.00
20              SOCIAL_CLASS              0        0.00
21            ROUTING_NUMBER              0        0.00
22  CUSTOMER_EDUCATION_LEVEL              0        0.00
47        VENDOR_POSTAL_CODE              0        0.00

In [76]:
col_name = null_df[null_df['Percentage']> 50]['ColumnName']
print('Shape of the DataFrame before removing the columns', final_df.shape)
print('Number of columns to be Drop:', len(col_name))
final_df.drop(col_name, axis = 1, inplace = True)

print('Shape of the DataFrame After removing the columns', final_df.shape)

Shape of the DataFrame before removing the columns (10000, 48)
Number of columns to be Drop: 3
Shape of the DataFrame After removing the columns (10000, 45)

In [88]:

def ratio_based_filling(df, column_name):
    ratio = df[column_name].value_counts(normalize=True)
    # Get the indices where the column has NaN values
    missing_indices = df[column_name].isna()
    
    # Use np.random.choice to randomly select a value based on the ratio
    df.loc[missing_indices, column_name] = np.random.choice(
        ratio.index, size=missing_indices.sum(), p=ratio.values
    )


ratio_based_filling(final_df, 'AGENT_CITY')
ratio_based_filling(final_df, 'VENDOR_CITY')

In [89]:
missing_values(final_df)

                  ColumnName  MissingValues  Percentage
0              TXN_DATE_TIME              0         0.0
23         INCIDENT_SEVERITY              0         0.0
25                ANY_INJURY              0         0.0
26   POLICE_REPORT_AVAILABLE              0         0.0
27            INCIDENT_STATE              0         0.0
28             INCIDENT_CITY              0         0.0
29  INCIDENT_HOUR_OF_THE_DAY              0         0.0
30                  AGENT_ID              0         0.0
31                 VENDOR_ID              0         0.0
32                AGENT_NAME              0         0.0
33           DATE_OF_JOINING              0         0.0
34       AGENT_ADDRESS_LINE1              0         0.0
35                AGENT_CITY              0         0.0
36               AGENT_STATE              0         0.0
37         AGENT_POSTAL_CODE              0         0.0
38        EMP_ROUTING_NUMBER              0         0.0
39           EMP_ACCT_NUMBER              0         0.0
40               VENDOR_NAME              0         0.0
41      VENDOR_ADDRESS_LINE1              0         0.0
42               VENDOR_CITY              0         0.0
43              VENDOR_STATE              0         0.0
24       AUTHORITY_CONTACTED              0         0.0
22              CLAIM_STATUS              0         0.0
1              POLICY_EFF_DT              0         0.0
21  CUSTOMER_EDUCATION_LEVEL              0         0.0
2                    LOSS_DT              0         0.0
3                  REPORT_DT              0         0.0
4             INSURANCE_TYPE              0         0.0
5             PREMIUM_AMOUNT              0         0.0
6               CLAIM_AMOUNT              0         0.0
7              CUSTOMER_NAME              0         0.0
8              ADDRESS_LINE1              0         0.0
9                       CITY              0         0.0
10                     STATE              0         0.0
11               POSTAL_CODE              0         0.0
12            MARITAL_STATUS              0         0.0
13                       AGE              0         0.0
14                    TENURE              0         0.0
15         EMPLOYMENT_STATUS              0         0.0
16      NO_OF_FAMILY_MEMBERS              0         0.0
17         RISK_SEGMENTATION              0         0.0
18                HOUSE_TYPE              0         0.0
19              SOCIAL_CLASS              0         0.0
20            ROUTING_NUMBER              0         0.0
44        VENDOR_POSTAL_CODE              0         0.0

In [90]:
final_df

,TXN_DATE_TIME,POLICY_EFF_DT,LOSS_DT,REPORT_DT,INSURANCE_TYPE,PREMIUM_AMOUNT,CLAIM_AMOUNT,CUSTOMER_NAME,ADDRESS_LINE1,CITY,STATE,POSTAL_CODE,MARITAL_STATUS,AGE,TENURE,EMPLOYMENT_STATUS,NO_OF_FAMILY_MEMBERS,RISK_SEGMENTATION,HOUSE_TYPE,SOCIAL_CLASS,ROUTING_NUMBER,CUSTOMER_EDUCATION_LEVEL,CLAIM_STATUS,INCIDENT_SEVERITY,AUTHORITY_CONTACTED,ANY_INJURY,POLICE_REPORT_AVAILABLE,INCIDENT_STATE,INCIDENT_CITY,INCIDENT_HOUR_OF_THE_DAY,AGENT_ID,VENDOR_ID,AGENT_NAME,DATE_OF_JOINING,AGENT_ADDRESS_LINE1,AGENT_CITY,AGENT_STATE,AGENT_POSTAL_CODE,EMP_ROUTING_NUMBER,EMP_ACCT_NUMBER,VENDOR_NAME,VENDOR_ADDRESS_LINE1,VENDOR_CITY,VENDOR_STATE,VENDOR_POSTAL_CODE
0,2020-06-01 00:00:00,2015-06-23,2020-05-16,2020-05-21,Health,157.13,9000,Christopher Demarest,7701 West Saint John Road,Glendale,AZ,85308,Y,54,89,Y,3,L,Own,LI,109134974,Bachelor,A,Major Loss,Police,0,1,GA,Savannah,4,AGENT00413,VNDR00556,Amy Wangler,1994-01-06,584 Rural Hill Road,Nashville,TN,37217,35441155,LRZO53254369804934,Ramsey Inc,3114 West 20th Court,Panama City,FL,32405
1,2020-06-01 00:00:00,2018-04-21,2020-05-13,2020-05-18,Property,141.71,26000,Ricardo Gatlin,8595 West 81st Drive,Arvada,CO,80005,N,61,80,Y,4,L,Rent,MI,40125819,Bachelor,A,Total Loss,Ambulance,1,0,AL,Montgomery,0,AGENT00769,VNDR00592,Jessica Montez,2004-05-28,6114 West Glenn Drive,Glendale,AZ,85301,44055451,XBYG14382904542874,"Morales, Campbell and Washington",42 West Louise Street,Fayetteville,AR,72701
2,2020-06-01 00:00:00,2019-10-03,2020-05-21,2020-05-26,Property,157.24,13000,Lashawn Engles,637 Britannia Drive,Vallejo,CA,94591,N,47,68,Y,6,L,Rent,MI,99513168,PhD,A,Total Loss,Police,0,1,CO,Grand Junction,19,AGENT00883,VNDR00031,Howard Smith,2004-08-01,2500 Snowdoun Chambers Road,Montgomery,AL,36105,55770246,WRXH14597428306333,Johnson Ltd,2619 North Quality Lane,Fayetteville,AR,72703
3,2020-06-01 00:00:00,2016-11-29,2020-05-14,2020-05-19,Health,172.87,16000,Steven Bassett,2803 River Drive,Thunderbolt,GA,31404,Y,36,16,Y,7,L,Mortgage,MI,18429110,Masters,A,Minor Loss,Ambulance,0,0,GA,Savannah,12,AGENT00278,VNDR00075,Patricia Tucker,2007-06-12,313 Lone Oak Drive,Norman,OK,73071,87652976,YEPN16077902472499,Blackwell-Foster,3609 Meadow Drive,Nashville,TN,37215
4,2020-06-01 00:00:00,2011-12-26,2020-05-17,2020-05-22,Travel,88.53,3000,Jason Rodriguez,7573 National Drive,Livermore,CA,94550,Y,51,16,Y,2,M,Rent,HI,70752391,Masters,A,Major Loss,Police,0,1,TN,Nashville,18,AGENT00636,VNDR00472,Brenda Bean,2010-01-19,120 Wells Avenue,Glen Burnie,MD,21061,76119019,HZBK86544578578547,Evans-Scott,4001 19th Place Northeast,Washington,DC,20018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2021-06-30 00:00:00,2014-04-11,2021-06-25,2021-06-26,Motor,105.75,1000,Patrick Hauman,126 Marjorie Lane,Manchester,CT,6042,N,45,98,Y,3,M,Own,MI,89109346,PhD,A,Minor Loss,Ambulance,1,1,CT,Manchester,0,AGENT00779,VNDR00001,Melissa Scott,1990-10-12,2723 East Joyce Boulevard,Fayetteville,AR,72703,35413882,LFOJ76068590051807,"King, Proctor and Jones",2027 North Shannon Drive,Fayetteville,AR,72703
9996,2021-06-30 00:00:00,2015-08-25,2021-06-12,2021-06-17,Life,64.59,67000,Paula Noel,501 West Maple Street,Fayetteville,AR,72701,Y,52,92,Y,3,L,Mortgage,LI,89666038,Masters,A,Total Loss,Police,1,0,MA,Worcester,6,AGENT00254,VNDR00598,Freda Dudley,2013-01-17,1363 Dean Forest Road,Savannah,GA,31405,91206790,AHEF60771774635030,"Newton, Hodges and Henry",32512 Christine Drive,Union City,CA,94587
9997,2021-06-30 00:00:00,2018-10-11,2021-06-18,2021-06-23,Health,183.50,8000,Luis Clark,10980 Splendor Loop,Anchorage,AK,99577,Y,53,32,Y,2,M,Mortgage,LI,34475591,Bachelor,A,Major Loss,Ambulance,1,1,OK,Oklahoma City,12,AGENT00786,VNDR00104,Victor Perrin,1993-02-11,9912 Shirewick Way,Louisville,KY,40272,115241097,WREH18805592939657,Reese-Mckinney,20 Garfield Street,Needham,MA,2492
9998,2021-06-30 00:00:00,2016-01-29,2021-06-16,2021-06-21,Motor,113.46,2000,Ryan Gordon,19 Heritage,Oakland,CA,94605,Y,61,44,Y,7,M,Rent,MI,59003728,Bachelor,A,Total Loss,Ambulance,0,1,AR,Fayetteville,6,AGENT00927,VNDR00185,Maria Lynn,2010-04-16,302 East Granada Street,Fayetteville,AR,72703,13995380,AAZI21883736448048,"Harmon, Manning and Bradley",1823 Dinger Road,Annapolis,MD,21402
9999,2021-06-30 00:00:00,2014-09-17,2021-06-21,2021-06-24,Mobile,8.22,300,Carol Clemons,3516 North Virginia Avenue,Oklahoma City,OK,73118,Y,64,106,Y,2,M,Rent,MI,102750957,Bachelor,A,Total Loss,Ambulance,1,0,CT,Manchester,13,AGENT00118,VNDR00163,Carl Balado,2007-10-26,1713 Apian Way,Edmond,OK,73003,39790996,RPES05613584687957,Foster-Sanchez,4255 Tanager Common,Fremont,CA,94555

In [94]:
final_df.drop(['ADDRESS_LINE1', 'AGENT_ADDRESS_LINE1', 'VENDOR_ADDRESS_LINE1'], axis =1, inplace = True)
final_df.drop(['CUSTOMER_NAME', 'ROUTING_NUMBER'], axis = 1, inplace = True) # more than 98.5% values are unique

In [109]:

final_df.TXN_DATE_TIME = pd.to_datetime(final_df.TXN_DATE_TIME).dt.date
final_df.POLICY_EFF_DT = pd.to_datetime(final_df.POLICY_EFF_DT).dt.date
final_df.LOSS_DT = pd.to_datetime(final_df.LOSS_DT).dt.date
final_df.REPORT_DT = pd.to_datetime(final_df.REPORT_DT).dt.date

In [110]:
#   LOSS_DATE must be less than or equal to the REPORT_DATE
final_df[final_df.LOSS_DT <= final_df.REPORT_DT]

,TXN_DATE_TIME,POLICY_EFF_DT,LOSS_DT,REPORT_DT,INSURANCE_TYPE,PREMIUM_AMOUNT,CLAIM_AMOUNT,CITY,STATE,POSTAL_CODE,MARITAL_STATUS,AGE,TENURE,EMPLOYMENT_STATUS,NO_OF_FAMILY_MEMBERS,RISK_SEGMENTATION,HOUSE_TYPE,SOCIAL_CLASS,CUSTOMER_EDUCATION_LEVEL,CLAIM_STATUS,INCIDENT_SEVERITY,AUTHORITY_CONTACTED,ANY_INJURY,POLICE_REPORT_AVAILABLE,INCIDENT_STATE,INCIDENT_CITY,INCIDENT_HOUR_OF_THE_DAY,AGENT_ID,VENDOR_ID,AGENT_NAME,DATE_OF_JOINING,AGENT_CITY,AGENT_STATE,AGENT_POSTAL_CODE,EMP_ROUTING_NUMBER,EMP_ACCT_NUMBER,VENDOR_NAME,VENDOR_CITY,VENDOR_STATE,VENDOR_POSTAL_CODE
0,2020-06-01,2015-06-23,2020-05-16,2020-05-21,Health,157.13,9000,Glendale,AZ,85308,Y,54,89,Y,3,L,Own,LI,Bachelor,A,Major Loss,Police,0,1,GA,Savannah,4,AGENT00413,VNDR00556,Amy Wangler,1994-01-06,Nashville,TN,37217,35441155,LRZO53254369804934,Ramsey Inc,Panama City,FL,32405
1,2020-06-01,2018-04-21,2020-05-13,2020-05-18,Property,141.71,26000,Arvada,CO,80005,N,61,80,Y,4,L,Rent,MI,Bachelor,A,Total Loss,Ambulance,1,0,AL,Montgomery,0,AGENT00769,VNDR00592,Jessica Montez,2004-05-28,Glendale,AZ,85301,44055451,XBYG14382904542874,"Morales, Campbell and Washington",Fayetteville,AR,72701
2,2020-06-01,2019-10-03,2020-05-21,2020-05-26,Property,157.24,13000,Vallejo,CA,94591,N,47,68,Y,6,L,Rent,MI,PhD,A,Total Loss,Police,0,1,CO,Grand Junction,19,AGENT00883,VNDR00031,Howard Smith,2004-08-01,Montgomery,AL,36105,55770246,WRXH14597428306333,Johnson Ltd,Fayetteville,AR,72703
3,2020-06-01,2016-11-29,2020-05-14,2020-05-19,Health,172.87,16000,Thunderbolt,GA,31404,Y,36,16,Y,7,L,Mortgage,MI,Masters,A,Minor Loss,Ambulance,0,0,GA,Savannah,12,AGENT00278,VNDR00075,Patricia Tucker,2007-06-12,Norman,OK,73071,87652976,YEPN16077902472499,Blackwell-Foster,Nashville,TN,37215
4,2020-06-01,2011-12-26,2020-05-17,2020-05-22,Travel,88.53,3000,Livermore,CA,94550,Y,51,16,Y,2,M,Rent,HI,Masters,A,Major Loss,Police,0,1,TN,Nashville,18,AGENT00636,VNDR00472,Brenda Bean,2010-01-19,Glen Burnie,MD,21061,76119019,HZBK86544578578547,Evans-Scott,Washington,DC,20018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2021-06-30,2014-04-11,2021-06-25,2021-06-26,Motor,105.75,1000,Manchester,CT,6042,N,45,98,Y,3,M,Own,MI,PhD,A,Minor Loss,Ambulance,1,1,CT,Manchester,0,AGENT00779,VNDR00001,Melissa Scott,1990-10-12,Fayetteville,AR,72703,35413882,LFOJ76068590051807,"King, Proctor and Jones",Fayetteville,AR,72703
9996,2021-06-30,2015-08-25,2021-06-12,2021-06-17,Life,64.59,67000,Fayetteville,AR,72701,Y,52,92,Y,3,L,Mortgage,LI,Masters,A,Total Loss,Police,1,0,MA,Worcester,6,AGENT00254,VNDR00598,Freda Dudley,2013-01-17,Savannah,GA,31405,91206790,AHEF60771774635030,"Newton, Hodges and Henry",Union City,CA,94587
9997,2021-06-30,2018-10-11,2021-06-18,2021-06-23,Health,183.50,8000,Anchorage,AK,99577,Y,53,32,Y,2,M,Mortgage,LI,Bachelor,A,Major Loss,Ambulance,1,1,OK,Oklahoma City,12,AGENT00786,VNDR00104,Victor Perrin,1993-02-11,Louisville,KY,40272,115241097,WREH18805592939657,Reese-Mckinney,Needham,MA,2492
9998,2021-06-30,2016-01-29,2021-06-16,2021-06-21,Motor,113.46,2000,Oakland,CA,94605,Y,61,44,Y,7,M,Rent,MI,Bachelor,A,Total Loss,Ambulance,0,1,AR,Fayetteville,6,AGENT00927,VNDR00185,Maria Lynn,2010-04-16,Fayetteville,AR,72703,13995380,AAZI21883736448048,"Harmon, Manning and Bradley",Annapolis,MD,21402
9999,2021-06-30,2014-09-17,2021-06-21,2021-06-24,Mobile,8.22,300,Oklahoma City,OK,73118,Y,64,106,Y,2,M,Rent,MI,Bachelor,A,Total Loss,Ambulance,1,0,CT,Manchester,13,AGENT00118,VNDR00163,Carl Balado,2007-10-26,Edmond,OK,73003,39790996,RPES05613584687957,Foster-Sanchez,Fremont,CA,94555

In [114]:
#   POLICY_EFFECTIVE_DATE must be less than or equal to the REPORT_DATE AMD LOSS_DATE
final_df[(final_df.POLICY_EFF_DT < final_df.REPORT_DT)& (final_df.POLICY_EFF_DT < final_df.LOSS_DT)]

,TXN_DATE_TIME,POLICY_EFF_DT,LOSS_DT,REPORT_DT,INSURANCE_TYPE,PREMIUM_AMOUNT,CLAIM_AMOUNT,CITY,STATE,POSTAL_CODE,MARITAL_STATUS,AGE,TENURE,EMPLOYMENT_STATUS,NO_OF_FAMILY_MEMBERS,RISK_SEGMENTATION,HOUSE_TYPE,SOCIAL_CLASS,CUSTOMER_EDUCATION_LEVEL,CLAIM_STATUS,INCIDENT_SEVERITY,AUTHORITY_CONTACTED,ANY_INJURY,POLICE_REPORT_AVAILABLE,INCIDENT_STATE,INCIDENT_CITY,INCIDENT_HOUR_OF_THE_DAY,AGENT_ID,VENDOR_ID,AGENT_NAME,DATE_OF_JOINING,AGENT_CITY,AGENT_STATE,AGENT_POSTAL_CODE,EMP_ROUTING_NUMBER,EMP_ACCT_NUMBER,VENDOR_NAME,VENDOR_CITY,VENDOR_STATE,VENDOR_POSTAL_CODE
0,2020-06-01,2015-06-23,2020-05-16,2020-05-21,Health,157.13,9000,Glendale,AZ,85308,Y,54,89,Y,3,L,Own,LI,Bachelor,A,Major Loss,Police,0,1,GA,Savannah,4,AGENT00413,VNDR00556,Amy Wangler,1994-01-06,Nashville,TN,37217,35441155,LRZO53254369804934,Ramsey Inc,Panama City,FL,32405
1,2020-06-01,2018-04-21,2020-05-13,2020-05-18,Property,141.71,26000,Arvada,CO,80005,N,61,80,Y,4,L,Rent,MI,Bachelor,A,Total Loss,Ambulance,1,0,AL,Montgomery,0,AGENT00769,VNDR00592,Jessica Montez,2004-05-28,Glendale,AZ,85301,44055451,XBYG14382904542874,"Morales, Campbell and Washington",Fayetteville,AR,72701
2,2020-06-01,2019-10-03,2020-05-21,2020-05-26,Property,157.24,13000,Vallejo,CA,94591,N,47,68,Y,6,L,Rent,MI,PhD,A,Total Loss,Police,0,1,CO,Grand Junction,19,AGENT00883,VNDR00031,Howard Smith,2004-08-01,Montgomery,AL,36105,55770246,WRXH14597428306333,Johnson Ltd,Fayetteville,AR,72703
3,2020-06-01,2016-11-29,2020-05-14,2020-05-19,Health,172.87,16000,Thunderbolt,GA,31404,Y,36,16,Y,7,L,Mortgage,MI,Masters,A,Minor Loss,Ambulance,0,0,GA,Savannah,12,AGENT00278,VNDR00075,Patricia Tucker,2007-06-12,Norman,OK,73071,87652976,YEPN16077902472499,Blackwell-Foster,Nashville,TN,37215
4,2020-06-01,2011-12-26,2020-05-17,2020-05-22,Travel,88.53,3000,Livermore,CA,94550,Y,51,16,Y,2,M,Rent,HI,Masters,A,Major Loss,Police,0,1,TN,Nashville,18,AGENT00636,VNDR00472,Brenda Bean,2010-01-19,Glen Burnie,MD,21061,76119019,HZBK86544578578547,Evans-Scott,Washington,DC,20018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2021-06-30,2014-04-11,2021-06-25,2021-06-26,Motor,105.75,1000,Manchester,CT,6042,N,45,98,Y,3,M,Own,MI,PhD,A,Minor Loss,Ambulance,1,1,CT,Manchester,0,AGENT00779,VNDR00001,Melissa Scott,1990-10-12,Fayetteville,AR,72703,35413882,LFOJ76068590051807,"King, Proctor and Jones",Fayetteville,AR,72703
9996,2021-06-30,2015-08-25,2021-06-12,2021-06-17,Life,64.59,67000,Fayetteville,AR,72701,Y,52,92,Y,3,L,Mortgage,LI,Masters,A,Total Loss,Police,1,0,MA,Worcester,6,AGENT00254,VNDR00598,Freda Dudley,2013-01-17,Savannah,GA,31405,91206790,AHEF60771774635030,"Newton, Hodges and Henry",Union City,CA,94587
9997,2021-06-30,2018-10-11,2021-06-18,2021-06-23,Health,183.50,8000,Anchorage,AK,99577,Y,53,32,Y,2,M,Mortgage,LI,Bachelor,A,Major Loss,Ambulance,1,1,OK,Oklahoma City,12,AGENT00786,VNDR00104,Victor Perrin,1993-02-11,Louisville,KY,40272,115241097,WREH18805592939657,Reese-Mckinney,Needham,MA,2492
9998,2021-06-30,2016-01-29,2021-06-16,2021-06-21,Motor,113.46,2000,Oakland,CA,94605,Y,61,44,Y,7,M,Rent,MI,Bachelor,A,Total Loss,Ambulance,0,1,AR,Fayetteville,6,AGENT00927,VNDR00185,Maria Lynn,2010-04-16,Fayetteville,AR,72703,13995380,AAZI21883736448048,"Harmon, Manning and Bradley",Annapolis,MD,21402
9999,2021-06-30,2014-09-17,2021-06-21,2021-06-24,Mobile,8.22,300,Oklahoma City,OK,73118,Y,64,106,Y,2,M,Rent,MI,Bachelor,A,Total Loss,Ambulance,1,0,CT,Manchester,13,AGENT00118,VNDR00163,Carl Balado,2007-10-26,Edmond,OK,73003,39790996,RPES05613584687957,Foster-Sanchez,Fremont,CA,94555

In [121]:
final_df['TRANSACTION_DAY'] = pd.to_datetime(final_df.TXN_DATE_TIME).dt.day
final_df['TRANSACTION_MONTH'] = pd.to_datetime(final_df.TXN_DATE_TIME).dt.month
final_df['TRANSACTION_YEAR'] = pd.to_datetime(final_df.TXN_DATE_TIME).dt.year

In [127]:
final_df['POLICY_EFF_DAY'] = pd.to_datetime(final_df.POLICY_EFF_DT).dt.day
final_df['POLICY_EFF_MONTH'] = pd.to_datetime(final_df.POLICY_EFF_DT).dt.month
final_df['POLICY_EFF_YEAR'] = pd.to_datetime(final_df.POLICY_EFF_DT).dt.year

In [128]:
final_df['LOSS_DAY'] = pd.to_datetime(final_df.LOSS_DT).dt.day
final_df['LOSS_MONTH'] = pd.to_datetime(final_df.LOSS_DT).dt.month
final_df['LOSS_YEAR'] = pd.to_datetime(final_df.LOSS_DT).dt.year

In [129]:
final_df['REPORT_DAY'] = pd.to_datetime(final_df.REPORT_DT).dt.day
final_df['REPORT_MONTH'] = pd.to_datetime(final_df.REPORT_DT).dt.month
final_df['REPORT_YEAR'] = pd.to_datetime(final_df.REPORT_DT).dt.year

In [130]:
final_df[[col for col in final_df.columns if 'DAY' in col or 'MONTH' in col or 'YEAR' in col or 'DT' in col or 'DATE' in col]]

,TXN_DATE_TIME,POLICY_EFF_DT,LOSS_DT,REPORT_DT,INCIDENT_HOUR_OF_THE_DAY,DATE_OF_JOINING,TRANSACTION_DAY,TRANSACTION_MONTH,TRANSACTION_YEAR,POLICY_EFF_DAY,POLICY_EFF_MONTH,POLICY_EFF_YEAR,LOSS_DAY,LOSS_MONTH,LOSS_YEAR,REPORT_DAY,REPORT_MONTH,REPORT_YEAR
0,2020-06-01,2015-06-23,2020-05-16,2020-05-21,4,1994-01-06,1,6,2020,23,6,2015,16,5,2020,21,5,2020
1,2020-06-01,2018-04-21,2020-05-13,2020-05-18,0,2004-05-28,1,6,2020,21,4,2018,13,5,2020,18,5,2020
2,2020-06-01,2019-10-03,2020-05-21,2020-05-26,19,2004-08-01,1,6,2020,3,10,2019,21,5,2020,26,5,2020
3,2020-06-01,2016-11-29,2020-05-14,2020-05-19,12,2007-06-12,1,6,2020,29,11,2016,14,5,2020,19,5,2020
4,2020-06-01,2011-12-26,2020-05-17,2020-05-22,18,2010-01-19,1,6,2020,26,12,2011,17,5,2020,22,5,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2021-06-30,2014-04-11,2021-06-25,2021-06-26,0,1990-10-12,30,6,2021,11,4,2014,25,6,2021,26,6,2021
9996,2021-06-30,2015-08-25,2021-06-12,2021-06-17,6,2013-01-17,30,6,2021,25,8,2015,12,6,2021,17,6,2021
9997,2021-06-30,2018-10-11,2021-06-18,2021-06-23,12,1993-02-11,30,6,2021,11,10,2018,18,6,2021,23,6,2021
9998,2021-06-30,2016-01-29,2021-06-16,2021-06-21,6,2010-04-16,30,6,2021,29,1,2016,16,6,2021,21,6,2021
9999,2021-06-30,2014-09-17,2021-06-21,2021-06-24,13,2007-10-26,30,6,2021,17,9,2014,21,6,2021,24,6,2021

In [141]:
final_df.drop(final_df.columns[:4], axis = 1, inplace = True)
final_df

,INSURANCE_TYPE,PREMIUM_AMOUNT,CLAIM_AMOUNT,CITY,STATE,POSTAL_CODE,MARITAL_STATUS,AGE,TENURE,EMPLOYMENT_STATUS,NO_OF_FAMILY_MEMBERS,RISK_SEGMENTATION,HOUSE_TYPE,SOCIAL_CLASS,CUSTOMER_EDUCATION_LEVEL,CLAIM_STATUS,INCIDENT_SEVERITY,AUTHORITY_CONTACTED,ANY_INJURY,POLICE_REPORT_AVAILABLE,INCIDENT_STATE,INCIDENT_CITY,INCIDENT_HOUR_OF_THE_DAY,AGENT_ID,VENDOR_ID,AGENT_NAME,DATE_OF_JOINING,AGENT_CITY,AGENT_STATE,AGENT_POSTAL_CODE,EMP_ROUTING_NUMBER,EMP_ACCT_NUMBER,VENDOR_NAME,VENDOR_CITY,VENDOR_STATE,VENDOR_POSTAL_CODE,TRANSACTION_DAY,TRANSACTION_MONTH,TRANSACTION_YEAR,POLICY_EFF_DAY,POLICY_EFF_MONTH,POLICY_EFF_YEAR,LOSS_DAY,LOSS_MONTH,LOSS_YEAR,REPORT_DAY,REPORT_MONTH,REPORT_YEAR
0,Health,157.13,9000,Glendale,AZ,85308,Y,54,89,Y,3,L,Own,LI,Bachelor,A,Major Loss,Police,0,1,GA,Savannah,4,AGENT00413,VNDR00556,Amy Wangler,1994-01-06,Nashville,TN,37217,35441155,LRZO53254369804934,Ramsey Inc,Panama City,FL,32405,1,6,2020,23,6,2015,16,5,2020,21,5,2020
1,Property,141.71,26000,Arvada,CO,80005,N,61,80,Y,4,L,Rent,MI,Bachelor,A,Total Loss,Ambulance,1,0,AL,Montgomery,0,AGENT00769,VNDR00592,Jessica Montez,2004-05-28,Glendale,AZ,85301,44055451,XBYG14382904542874,"Morales, Campbell and Washington",Fayetteville,AR,72701,1,6,2020,21,4,2018,13,5,2020,18,5,2020
2,Property,157.24,13000,Vallejo,CA,94591,N,47,68,Y,6,L,Rent,MI,PhD,A,Total Loss,Police,0,1,CO,Grand Junction,19,AGENT00883,VNDR00031,Howard Smith,2004-08-01,Montgomery,AL,36105,55770246,WRXH14597428306333,Johnson Ltd,Fayetteville,AR,72703,1,6,2020,3,10,2019,21,5,2020,26,5,2020
3,Health,172.87,16000,Thunderbolt,GA,31404,Y,36,16,Y,7,L,Mortgage,MI,Masters,A,Minor Loss,Ambulance,0,0,GA,Savannah,12,AGENT00278,VNDR00075,Patricia Tucker,2007-06-12,Norman,OK,73071,87652976,YEPN16077902472499,Blackwell-Foster,Nashville,TN,37215,1,6,2020,29,11,2016,14,5,2020,19,5,2020
4,Travel,88.53,3000,Livermore,CA,94550,Y,51,16,Y,2,M,Rent,HI,Masters,A,Major Loss,Police,0,1,TN,Nashville,18,AGENT00636,VNDR00472,Brenda Bean,2010-01-19,Glen Burnie,MD,21061,76119019,HZBK86544578578547,Evans-Scott,Washington,DC,20018,1,6,2020,26,12,2011,17,5,2020,22,5,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Motor,105.75,1000,Manchester,CT,6042,N,45,98,Y,3,M,Own,MI,PhD,A,Minor Loss,Ambulance,1,1,CT,Manchester,0,AGENT00779,VNDR00001,Melissa Scott,1990-10-12,Fayetteville,AR,72703,35413882,LFOJ76068590051807,"King, Proctor and Jones",Fayetteville,AR,72703,30,6,2021,11,4,2014,25,6,2021,26,6,2021
9996,Life,64.59,67000,Fayetteville,AR,72701,Y,52,92,Y,3,L,Mortgage,LI,Masters,A,Total Loss,Police,1,0,MA,Worcester,6,AGENT00254,VNDR00598,Freda Dudley,2013-01-17,Savannah,GA,31405,91206790,AHEF60771774635030,"Newton, Hodges and Henry",Union City,CA,94587,30,6,2021,25,8,2015,12,6,2021,17,6,2021
9997,Health,183.50,8000,Anchorage,AK,99577,Y,53,32,Y,2,M,Mortgage,LI,Bachelor,A,Major Loss,Ambulance,1,1,OK,Oklahoma City,12,AGENT00786,VNDR00104,Victor Perrin,1993-02-11,Louisville,KY,40272,115241097,WREH18805592939657,Reese-Mckinney,Needham,MA,2492,30,6,2021,11,10,2018,18,6,2021,23,6,2021
9998,Motor,113.46,2000,Oakland,CA,94605,Y,61,44,Y,7,M,Rent,MI,Bachelor,A,Total Loss,Ambulance,0,1,AR,Fayetteville,6,AGENT00927,VNDR00185,Maria Lynn,2010-04-16,Fayetteville,AR,72703,13995380,AAZI21883736448048,"Harmon, Manning and Bradley",Annapolis,MD,21402,30,6,2021,29,1,2016,16,6,2021,21,6,2021
9999,Mobile,8.22,300,Oklahoma City,OK,73118,Y,64,106,Y,2,M,Rent,MI,Bachelor,A,Total Loss,Ambulance,1,0,CT,Manchester,13,AGENT00118,VNDR00163,Carl Balado,2007-10-26,Edmond,OK,73003,39790996,RPES05613584687957,Foster-Sanchez,Fremont,CA,94555,30,6,2021,17,9,2014,21,6,2021,24,6,2021

In [142]:
final_df.to_csv('Datasets/Combined_data.csv', index = False)